name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'loan-backend/**'

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Build the backend application
    - name: Build Backend Application
      run: |
        cd ~/actions-runner/_work/loan-assignment/loan-assignment/loan-backend
        npm install
        npm run build

    # Restart the PM2 process
    - name: Restart Backend with PM2
      run: |
        cd ~/actions-runner/_work/loan-assignment/loan-assignment/loan-backend
        pm2 restart app