name: CI for Backend and Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-ci:
    runs-on: self-hosted

    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v3
        with:
          path: backend
      
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

  client-ci:
    runs-on: self-hosted

    steps:
      - name: Checkout Client Code
        uses: actions/checkout@v3
        with:
          path: client
      
      - name: Install Client Dependencies
        run: |
          cd client
          npm install

      - name: Run Client Tests
        run: |
          cd client
          npm test